name: Greetings
#on: [pull_request, issues]
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
jobs:
  greeting:
    runs-on: ubuntu-latest
    #permissions:
      #pull-requests: write
      #issues: write
    steps:
    - uses: actions/first-interaction@v1
    # At this moment, this GitHub Action has an issue: https://github.com/actions/first-interaction/issues/101
    # In order to try to solve this, we use this: https://github.com/keploy/keploy/pull/182/files 
    # continue-on-error: true
    # Finally, this issue is solved by this PR https://github.com/actions/first-interaction/pull/103 so no need to use that condition anymore
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'NGcodeX: Thanks for opening your first issue 😊 ! We really appreciate your work. Happy Coding 🎉🎊 !'
        pr-message: 'NGcodeX: Thanks for opening your first pull request 😊 ! We really appreciate your work. Happy Coding 🎉🎊 !'
